<?php
namespace backend\controllers;
use \yii\web\Controller;
use yii\filters\VerbFilter;

class AdminBaseController extends Controller{
    public $layout = 'main';
    public $languageId = 1;


    public function __construct(string $id, $module, array $config = [])
    {
        parent::__construct($id, $module, $config);

        // INPUT
        $this->languageId = (\Yii::$app->request->get('languageId') > 0) ? \Yii::$app->request->get('languageId') : 1;
    }

    /**
     * Init
     */
    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub

        //print_r($_GET['language']); die();

        $app = \Yii::$app;

        if(isset($app->session['languageId']))
        {
            $app->language = $app->session['languageId'];
        }else{
            // default en
            $session = \Yii::$app->session;
            $session->set('languageId', \Yii::$app->language);
        }
    }


    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

}